spring:
  application:
    name: product-cache-service

  main:
    allow-bean-definition-overriding: true
info:
  componen: Product Cache Service
logging:
  level:
    com.example.productcacheservice: debug
server:
  port: 9792
---
spring:
  profiles:
    active: localhost
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
feign:
  product-service:
    name: car-service
    url: http://localhost:8081
---
# eureka:
 # client:
 #   service-url:
#      default-zone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10

