spring:
  application:
    name: config-server
  profiles:
    active: localhost

info:
  component: Config Server

---
spring:
  profiles: localhost
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GiyasRzza/configs-server.git
logging:
  level:
    root: debug
server:
  port: 8888
---
