# version: '3.8'
# services:
#   db:
#     image: mysql:8.0
#     cap_add:
#       - SYS_NICE
#     restart: always
#     network: 
#        -  stock-app  
#     environment:
#       MYSQL_DATABASE: product
#       MYSQL_USER: root
#       MYSQL_PASSWORD: searcher
#     ports:
#       - '3306:3306'
#     volumes:
#       - db:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
# volumes:
#   db:
#     driver: local
version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: searcher
      MYSQL_DATABASE: product
      MYSQL_USER: root
      MYSQL_PASSWORD: searcher
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
