version: '3'
services:
  spring-app:
    image: product-service:0.0.1
    container_name: product-service
    hostname: product-service
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
